# Generated by Django 2.2.4 on 2019-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='icon_of_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/UniLogo')),
            ],
        ),
        migrations.CreateModel(
            name='news_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=75, null=True)),
                ('Image', models.ImageField(upload_to='images/NewsPhotos/')),
                ('Text', models.TextField(blank=True, max_length=2048, null=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoTag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='uni_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniName', models.CharField(max_length=250)),
                ('UniWorkTime', models.CharField(blank=True, max_length=250, null=True)),
                ('UniGmail', models.CharField(max_length=250)),
                ('UniNumber', models.CharField(max_length=250)),
                ('UniUrl', models.URLField(blank=True, null=True)),
                ('UniAdressForLink', models.CharField(max_length=100, verbose_name='This link will redirect to the google Maps')),
                ('UniAdressForUser', models.CharField(max_length=100, verbose_name='This is the readible link  for User')),
                ('UniImage1', models.ImageField(upload_to='images/UniLogos/', verbose_name='Logo Image(should_be_added)')),
                ('UniImage2', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage3', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage4', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage5', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage6', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage7', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage8', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage9', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage10', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage11', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage12', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage13', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage14', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
                ('UniImage15', models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/')),
            ],
        ),
    ]
