# Generated by Django 2.2.4 on 2019-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='UniData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
