# Generated by Django 2.2.4 on 2019-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190816_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='UniAdressForLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniAdressForUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
