# Generated by Django 2.2.4 on 2019-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190816_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForLink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='This link will redirect to the google Maps'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForUser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='This is the readible link  for User'),
        ),
    ]
