# Generated by Django 2.2.4 on 2019-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190816_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoTag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniImage11',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniLogos/'),
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniImage12',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniLogos/'),
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniImage13',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniLogos/'),
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniImage14',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniLogos/'),
        ),
        migrations.AddField(
            model_name='uni_list',
            name='UniImage15',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniLogos/'),
        ),
    ]
