# Generated by Django 2.2.4 on 2019-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190817_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForLink',
            field=models.CharField(max_length=100, verbose_name='This link will redirect to the google Maps'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForUser',
            field=models.CharField(max_length=100, verbose_name='This is the readible link  for User'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage11',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage12',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage13',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage14',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage15',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/'),
        ),
    ]
