# Generated by Django 2.2.4 on 2019-08-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190821_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_list',
            name='UniGmail',
        ),
    ]
