# Generated by Django 2.2.4 on 2019-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_uni_list_unigmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='UniGmail',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniNumber',
            field=models.IntegerField(max_length=250),
        ),
    ]
