# Generated by Django 2.2.4 on 2019-08-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190822_0005'),
        ('mainapp', '0010_auto_20190822_0101'),
    ]

    operations = [
    ]
