# Generated by Django 2.2.4 on 2019-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20190822_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='UniWorkTime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
