# Generated by Django 2.2.4 on 2019-08-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190822_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='UniStudentsCount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
