# Generated by Django 2.2.4 on 2019-08-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_uni_list_unistudentscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='UniYear',
            field=models.IntegerField(default=2019),
        ),
    ]
