# Generated by Django 2.2.4 on 2019-08-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190823_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni_list',
            old_name='UniMaxCountOfMoney',
            new_name='UniMinPayment',
        ),
        migrations.RemoveField(
            model_name='uni_list',
            name='UniMinCountOfMoney',
        ),
    ]
