# Generated by Django 2.2.4 on 2019-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190823_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='UniMaxPayment',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniMinPayment',
            field=models.IntegerField(default=1000),
        ),
    ]
