# Generated by Django 2.2.4 on 2019-08-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190823_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_list',
            name='Dormitory',
            field=models.CharField(choices=[('Yes', 'No')], default=('Yes', 'No'), max_length=100),
        ),
    ]
