# Generated by Django 2.2.4 on 2019-08-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20190823_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='Dormitory',
            field=models.CharField(choices=[('Yes', 'No')], default='No', max_length=100),
        ),
    ]
