# Generated by Django 2.2.4 on 2019-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20190905_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForLink',
            field=models.CharField(max_length=250, verbose_name='Universitetin user gördüyü linki:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForUser',
            field=models.CharField(max_length=250, verbose_name='Universitetin google map üçün linki:'),
        ),
    ]
