# Generated by Django 3.0.3 on 2020-03-07 22:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20190905_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='Date',
            field=models.DateField(verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='Image',
            field=models.ImageField(upload_to='images/NewsPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='Text',
            field=models.TextField(blank=True, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='Title',
            field=models.CharField(max_length=300, null=True, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='Dormitory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='Dormitory:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForLink',
            field=models.CharField(max_length=250, verbose_name='Google map link:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniAdressForUser',
            field=models.CharField(max_length=250, verbose_name='Adress:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage1',
            field=models.ImageField(upload_to='images/UniLogos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage10',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage11',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage12',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage13',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage14',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage15',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage2',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage3',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage4',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage5',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage6',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage7',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage8',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniImage9',
            field=models.ImageField(blank=True, null=True, upload_to='images/UniPhotos/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniMaxPayment',
            field=models.IntegerField(default=1500, verbose_name='Min University fee:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniMinPayment',
            field=models.IntegerField(default=1000, verbose_name='Min University fee:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniName',
            field=models.CharField(max_length=250, verbose_name='University name:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniNumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Contact number:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniStudentsCount',
            field=models.FloatField(blank=True, null=True, verbose_name='Student count:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniWebsite',
            field=models.URLField(blank=True, null=True, verbose_name='Website:'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniWorkTime',
            field=models.TextField(blank=True, null=True, verbose_name='University work hours'),
        ),
        migrations.AlterField(
            model_name='uni_list',
            name='UniYear',
            field=models.IntegerField(default=2020, verbose_name='Year:'),
        ),
    ]
